spring:
  application:
    name: UserCenter
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jack
    username: root
    password: R_c83aQtuk5e
server:
  port: 8080
